package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"Bank_graphqlWS/graph/model"
	"context"
)

// CreateBankAccount is the resolver for the createBankAccount field.
func (r *mutationResolver) CreateBankAccount(ctx context.Context, input model.CreateBankAccountInput) (*model.Bank, error) {
	return r.Resolver.CreateBankAccount(ctx, input)
}

// CanBuyCar is the resolver for the canBuyCar field.
func (r *mutationResolver) CanBuyCar(ctx context.Context, carID int32, id int32) (string, error) {
	return r.Resolver.CanBuyCar(ctx, carID, id)
}

// CreateInsurance is the resolver for the createInsurance field.
func (r *mutationResolver) CreateInsurance(ctx context.Context, input model.CreateInsuranceInput) (*model.Insurance, error) {
	return r.Resolver.CreateInsurance(ctx, input)
}

// GetBankAccountByID is the resolver for the getBankAccountById field.
func (r *queryResolver) GetBankAccountByID(ctx context.Context, id string) (*model.Bank, error) {
	return r.Resolver.GetBankAccountById(ctx, id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
