// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bank struct {
	ID            string  `json:"ID"`
	AccountNumber string  `json:"AccountNumber"`
	Balance       float64 `json:"Balance"`
	UserID        int32   `json:"UserID"`
}

type CreateBankAccountInput struct {
	ID            string  `json:"Id"`
	AccountNumber string  `json:"accountNumber"`
	Balance       float64 `json:"balance"`
	UserID        int32   `json:"userId"`
}

type CreateInsuranceInput struct {
	ID         string `json:"id"`
	PurchaseID int32  `json:"purchaseId"`
}

type Insurance struct {
	ID             string  `json:"id"`
	PurchaseID     int32   `json:"purchaseId"`
	UserID         int32   `json:"userId"`
	CarID          int32   `json:"carId"`
	DateOfContract string  `json:"dateOfContract"`
	Deadline       string  `json:"deadline"`
	Amount         float64 `json:"amount"`
	CompanyName    string  `json:"companyName"`
}

type Mutation struct {
}

type Query struct {
}
